### ISSUE TITLE
use https://github.com/hashicorp/setup-terraform instead of bin/terraform*

### ISSUE THREAD

**Issue by Slach** [diggerhq/tfrun#3]
bin folder looks a little bit  ugly

**Comment by ZIJ** [comment]
Thanks so much for creating the issue @Slach ! Great idea, we will look into it

**Comment by motatoes** [comment]
That's a good idea, I'm going to try it out in tfrun demo repository to see how well it works if so we can adopt this approach of installation within external action, if it works well we can adopt it here

**Comment by motatoes** [comment]
Completed in [this commit](https://github.com/diggerhq/tfrun/commit/a757c2921a995d8438abca5d620a86da61403665) and update the [demo project too](https://github.com/diggerhq/tfrun_demo/blob/4124a3a9307f8fe5fa68b5e614b442a55782da45/.github/workflows/plan.yml#L39) to use setup-terraform
